# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3 # Pull-uje kod u virtuelnu masinu.
      - name: Use Node.js ${{ matrix.node-version }} # Prikazuje poruku u konzoli
        uses: actions/setup-node@v3 # Instalira node
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci # Clean install
      - run: npm run build --if-present # Ako postoji skripta, porece je
      - run: npm test
      - run: |
        echo Trenutno se nalazite u: 
        pwd
        ls -la

  #     - name: Archive production artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: demo-app-build-prod
  #         path: build/

  # deploy:
  #   needs: build_and_test
  #   runs-on: ubuntu-latest
  #   name: 'Deploy to Netlify'
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: demo-app-build-prod
  #     - uses: jsmrcaga/action-netlify-deploy@v1.1.0
  #       with:
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.MY_DEMO_APP_NETLIFY_TOKEN }}
  #         NETLIFY_DEPLOY_TO_PROD: true     
